name: NekoCraftCore
main: neko\catcore\nekocore
version: 6.0.0alpha
api: [2.0.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1,3.0.0-ALPHA5]
load: POSTWORLD
author: NekoGirl678
description: MeowCraft
commands:
 Sukottoss:
  description: Sukos Command he made
  usage: "Usage: /Sukottoss"
  permission: catcore.command.*
 yawn:
  description: Yawn
  usage: "Usage: /yawn"
  permission: catcore.command.*
 snuggle:
  description: Snuggle
  usage: "Usage: /snuggle <player>"
  permission: catcore.command.*
 cathelp:
  description: CatCraft Help
  usage: "Usage: /cathelp"
  permission: catcore.command.cathelp
 roleplaytools:
  description: RolePlay Tools
  usage: "Usage: /roleplaytools <page:help:permissions>"
  permission: catcore.rp.command.roleplaytools
 sleep:
  description: Fall Asleep
  usage: "Usage: /sleep"
  permission: catcore.rp.command.sleep
 iam:
  description: do something
  usage: "Usage: /iam <message>"
  permission: catcore.rp.command.iam
 hiss:
  description: Hiss like a cat
  usage: "Usage: /hiss"
  permission: catcore.rp.command.hiss
 purr:
  description: Purr like a cat
  usage: "Usage: /purr"
  permission: catcore.rp.command.purr
 meow:
  description: Meow like a cat
  usage: "Usage: /meow"
  permission: catcore.rp.command.meow
 poke:
  description: Poke People
  usage: "/poke <Player>"
  permission: catcore.rp.command.poke
 setdeathmessage:
  description: Set the death message
  usage: "/setdeathmessage <string>"
  permission: catcore.command.sdm
 setscore:
  description: Set the score of a player
  usage: "/setscore <Player> <amount>"
  permission: catcore.command.setscore
 addscore:
  description: Add the Score to a player
  usage: "/addscore <Player> <amount>"
  permission: catcore.command.addscore
 rmscore:
  description: Subtracts the score of a Player
  usage: "/rmscore <Player> <amount>"
  permission: catcore.command.rmscore
 nya:
  description: Nya Nya
  usage: "Usage: /nya"
  permission: catcore.rp.command.nya
 grr:
  description: GRRRRR
  usage: "Usage: /grr"
  permission: catcore.rp.command.grr
 sneeze:
  description: Sneeze
  usage: "Usage: /sneeze"
  permission: catcore.rp.command.sneeze
 emoji:
  description: Emoji
  usage: "Usage: /emoji <mad:happy:sad:funny:irritated:lovey:sly:sneaky:sick>"
  permission: catcore.rp.command.emoji
 facepalm:
  description: Facepalm over something
  usage: "Usage: /facepalm"
  permission: catcore.rp.command.facepalm
 score:
  description: Shows CatCraft User Score
  usage: "Usage: /score"
  permission: catcore.command.score
 staff:
  description: Staff Main command
  usage: "Usage: /staff <help|list|add|remove>"
  permission: catcore.command.staff
 setwelcomemessage:
  description: Set the servers join message
  usage: "Usage: /setwelcomemessage <msg>"
  permission: catcore.command.setwelcomemessage
 Suko:
  description: Special thanks to
  usage: "Usage: /Suko"
  permission: catcore.command.suko
permissions:
 catcore.rp.*:
  description: "Allows user to use all Roleplay features!"
  default: op
 catcore.rp.command.*:
  decription: "Allows user to use all the Roleplay commands!"
  default: true
 catcore.rp.command.facepalm:
  description: "Allows user to facepalm!"
  default: true
 catcore.rp.command.roleplaytools:
  description: "Allows user to use the rptools command"
  default: true
 catcore.rp.command.emoji:
  description: "Allows user to use Emoji command!"
  default: true
 catcore.rp.command.meow:
  description: "Allows user to use the Meow command!"
  default: true
 catcore.rp.command.hiss:
  description: "Allows user to use the Hiss command!"
  default: true
 catcore.rp.command.purr:
  description: "Allows user to use the Purr command!"
  default: true
 catcore.rp.command.sleep:
  description: "Allows user to use the Sleep command!"
  default: true
 catcore.rp.command.iam:
  description: "Allows user to use the Iam command!"
  default: true
 catcore.rp.command.sneeze:
  description: "Allows user to use the Sneeze command!"
  default: true
 catcore.rp.command.nya:
  description: "Allows user to use the Nya command!"
  default: true
 catcore.rp.command.grr:
  description: "Allows user to use the Grr command!"
  default: true
 catcore.rp.command.poke:
  description: "Allows user to use the Poke command!"
  default: true
 catcore.command.cathelp:
  description: "Allows user to use NekoCraft help"
  default: true
 catcore.command.score:
  description: "Allows user to view NekoCraft High Score"
  default: true
 catcore.command.setscore:
  description: "Allows user to set a player's score"
  default: op
 catcore.command.addscore:
  description: "Allows user to add a player's score"
  default: op
 catcore.command.rmscore:
  description: "Allows user to subtract a player's score"
  default: op
 catcore.command.staff:
  description: "Allows user to use NekoCraft Stafflist"
  default: true
 catcore.command.setwelcomemessage:
  description: "Allows user to use NekoCraft Set welcome message"
  default: op
 catcore.command.sdm:
  description: "Allows user to set the death message"
  default: op
 catcore.command.suko:
  description: "Allows user to find out a really good person"
  default: true
 catcore.command.*:
  description: "Allows user to use all NekoCraft's commands"
  default: op
 catcore.*:
  description: "Allows user to use all of NekoCraft's features"
  default: op
