name: NekoCraftCore
main: neko\catcore\nekocore
version: 4.1.77356
api: [2.0.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1]
load: POSTWORLD
author: NekoGirl678
description: MeowCraft
commands:
 cathelp:
  description: CatCraft Help
  usage: "Usage: /cathelp"
  permission: catcore.command.cathelp
 score:
  description: Shows CatCraft User Score
  usage: "Usage: /score"
  permission: catcore.command.score
 staff:
  description: Staff Main command
  usage: "Usage: /staff <help|list|add|remove>"
  permission: catcore.command.staff
 setwelcomemessage:
  description: Set the servers join message
  usage: "Usage: /setwelcomemessage <msg>"
  permission: catcore.command.setwelcomemessage
 Suko:
  description: Special thanks to
  usage: "Usage: /Suko"
  permission: catcore.command.suko
permissions:
 catcore.command.cathelp:
  description: "Allows user to use NekoCraft help"
  default: true
 catcore.command.score:
  description: "Allows user to view NekoCraft High Score"
  default: true
 catcore.command.staff:
  description: "Allows user to use NekoCraft Stafflist"
  default: true
 catcore.command.setwelcomemessage:
  description: "Allows user to use NekoCraft Set welcome message"
  default: op
 catcore.command.suko:
  description: "Allows user to find out a really good person"
  default: true
 catcore.command.*:
  description: "Allows user to use all NekoCraft's commands"
  default: op
 catcore.*:
  description: "Allows user to use all of NekoCraft's features"
  default: op
